name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist


       # Configurar las credenciales de GitHub para el despliegue
      - name: Desplegar a GitHub Pages..
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd dist
          git init
          git add .
          git commit -m "GitHub Actions Build desde .yml"

          git remote add gh-pages-remote https://github.com/PiaAchigar/Almacen.git

          git push --force gh-pages-remote master:gh-pages
       
